/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a9aa23c5-69b2-498b-a7c5-c927de29c60f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XcHTTmqnD",
    "aws_user_pools_web_client_id": "1aoe5226002guuo3auqig0bcee",
    "oauth": {
        "domain": "funcappamplifyebefd711-ebefd711-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apicc0fcf00",
            "endpoint": "https://v4e84f8m62.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://mbp2drwa4fbbrcfyeoltvdezb4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_mobile_analytics_app_id": "c1a8a496fb6d4b519b32a17c4214b69d",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "funcappamplifydbcb4acd6de34179ae31b910cc516a69120746-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "predictions": {
        "convert": {
            "translateText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "en",
                    "targetLanguage": "es"
                }
            }
        }
    }
};


export default awsmobile;
